Repository owncloud/files_primary_s3, pull requests merged in 2018-08, with the labels that each got.

#109 Use core acceptance tests run.sh
  .drone.yml
Labels: 3 - Review

#110 Remove unneeded SKELETON_DIR in .drone.yml
  .drone.yml
Labels: 3 - Review

#114 Version bumps for dependencies
  composer.lock
Labels: 3 - Review, dependencies

#112 Rename command s3:ls to s3:list
  appinfo/info.xml
  lib/command/s3list.php
Labels: 3 - To review

#118 Create README.md
  README.md
Labels: 3 - To review

#122 su-exec www-data is not needed for acceptance tests
  .drone.yml
Labels: 3 - To review, QA-team, dev:acceptance-tests
