Repository owncloud/files_primary_s3, pull requests merged in 2019-03, with the labels that each got.

#191 Drop PHP 5.6
  .drone.yml
Labels: 3 - To review, QA-team

#193 Adjust composer files and app core min-version for 'drop PHP 5.6'
  appinfo/info.xml
  composer.json
  composer.lock
  vendor-bin/behat/composer.json
Labels: 4 - To release, QA-team

#197 disable integrity check for tests
  .drone.yml
Labels: 3 - To review, QA-team, dev:acceptance-tests

#198 Split core tests
  .drone.yml
Labels: 4 - To release, QA-team, dev:acceptance-tests
