Repository owncloud/files_primary_s3, pull requests merged in 2019-01, with the labels that each got.

#172 loop when creating bucket for testing
  .drone.yml
  tests/drone/create-bucket.sh
Labels: 4 - To release, QA-team

#174 Use GNU format for tar
  Makefile
Labels: 3 - To review

#177 Release 1.0.3
  CHANGELOG.md
  Makefile
  appinfo/info.xml
Labels: 3 - To review

#181 Install and run behat from vendor-bin
  Makefile
  vendor-bin/behat/composer.json
Labels: 4 - To release, QA-team, dev:acceptance-tests
