Repository owncloud/files_primary_s3, pull requests merged in 2019-12, with the labels that each got.

#281 Allow behat to locally find guzzle and phpunit
  .drone.starlark
  .drone.yml
  vendor-bin/behat/composer.json
Labels: 3 - To review, QA-team

#285 Add sabre/xml to behat dependencies
  .drone.starlark
  .drone.yml
  vendor-bin/behat/composer.json
Labels: 3 - To review, QA-team, dev:acceptance-tests

#286 Increase wait-for-db timeout from 120 to 600 seconds
  .drone.starlark
  .drone.yml
Labels: 3 - To review, Drone, QA-team

#288 Implement coding-standard 2.0.0
  vendor-bin/owncloud-codestyle/composer.json
Labels: 4 - To release, QA-team

#287 Format message thrown by AWS exception
  lib/s3storage.php
Labels: 3 - To review

#297 Increase numberOfParts in drone due to core 36629
  .drone.starlark
  .drone.yml
Labels: 4 - To release, Drone, QA-team
