Repository owncloud/files_primary_s3, pull requests merged in 2020-03, with the labels that each got.

#317 [Tests-only] run smoke tests on s3.isv.scality.com
  .drone.star
  Makefile
  tests/delete_all_object_versions.sh
Labels: 4 - To release, QA-team, dev:acceptance-tests

#320 [Tests-Only] Apply latest .drone.star code
  .drone.star
Labels: 3 - To review, QA-team, dev:acceptance-tests

#322 Pin behat/mink to 1.7.1 and update other acceptance test dependencies
  .drone.star
  vendor-bin/behat/composer.json
Labels: 4 - To release, QA-team, dev:acceptance-tests

#323 Bugfix/l10n
  .gitignore
  Makefile
  l10n/.tx/config
  l10n/de.js
  l10n/de.json
  lib/s3storage.php
Labels: 3 - To review

#325 l10n makefile targets need no composer
  Makefile
Labels: 3 - To review

#329 Fix Makefile indent of ifndef
  Makefile
Labels: QA-team

#330 [1.1.2] Fix Makefile indent of ifndef
  Makefile
Labels: 3 - To review
