Repository owncloud/files_primary_s3, pull requests merged in 2020-04, with the labels that each got.

#334 Updating symfony/polyfill-mbstring (v1.14.0 => v1.15.0) and aws-sdk-php
  composer.lock
Labels: 3 - To review, dependencies

#336 [Tests-Only] Update phpstan to latest version
  lib/streamwrapper.php
  phpstan.neon
  vendor-bin/phpstan/composer.json
Labels: 4 - To release, QA-team

#337 Drop PHP 7.1
  .drone.star
  composer.json
  composer.lock
Labels: 4 - To release, QA-team

#340 [release-1.1.2] Add l10n to dist/appstore build
  .drone.star
  Makefile
  composer.json
  composer.lock
  l10n/he.js
  l10n/he.json
  l10n/ru.js
  l10n/ru.json
  lib/streamwrapper.php
  phpstan.neon
  vendor-bin/phpstan/composer.json
Labels: 4 - To release

#341 [Tests-Only] Bump phan 2.7
  lib/streamwrapper.php
  vendor-bin/phan/composer.json
Labels: QA-team

#344 Implement phpunit v8
  vendor-bin/behat/composer.json
Labels: 3 - To review, QA-team

#349 Adjust drone pipelines for PHP 7.4
  .drone.star
  .gitignore
Labels: 4 - To release, QA-team
