Repository owncloud/files_primary_s3, pull requests merged in 2020-02, with the labels that each got.

#309 Add phpdoc for Symfony Command execute
  lib/command/createbucket.php
  lib/command/s3list.php
Labels: 3 - To review

#310 Update starlark code 20200208
  .drone.star
  .drone.yml
Labels: 3 - To review, Drone, QA-team

#313 [Tests-only] guzzle version updated
  vendor-bin/behat/composer.json
Labels: 3 - To review, QA-team

#316 Update PHP dependencies
  composer.lock
Labels: 3 - To review, dependencies

#318 [Tests-Only] Run core API tests with scality
  .drone.star
Labels: 3 - To review, Drone, QA-team
